config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainapp.urls")),
    path("account/", include("account.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views


app_name = "mainapp"


urlpatterns = [
    path("", views.ReadmeView.as_view(), name="readme_page"),
    path("entries/", views.EntryListView.as_view(), name="entries_page"),
    path("statistic/", views.StatisticListView.as_view(), name="statistic_page"),
    path("create-entry/", views.CreateEntry.as_view(), name="create_entry_page"),
    path("update-entry/<int:pk>/", views.EntryUpdateView.as_view(), name="update_entry_page"),
    path("entry/<int:pk>/", views.EntryDetailView.as_view(), name="entry_detail_page"),
    path("delete-entry/<int:pk>/", views.EntryDeleteView.as_view(), name="entry_delete_page"),
]

mainapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class EntryModel(models.Model):
    """модель записи"""
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    title = models.CharField(verbose_name="Название", max_length=255)
    distance = models.FloatField(verbose_name="Расстояние")
    duration = models.FloatField(verbose_name="Продолжительность времени")
    date = models.DateTimeField(verbose_name="Дата создания записи", auto_now_add=True)
    average_speed = models.FloatField(verbose_name="Средняя скорость", null=True, blank=True)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return "/entries/"

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"


class StatisticModel(models.Model):
    """модель статистики"""
    year = models.PositiveSmallIntegerField(verbose_name="Год")
    week_number = models.PositiveSmallIntegerField(verbose_name="Номер недели")
    entry = models.ManyToManyField(EntryModel, verbose_name="Запись", blank=True)

    def __str__(self):
        return f"year: {self.year}, week: {self.week_number}"

    class Meta:
        verbose_name = "Статистику"
        verbose_name_plural = "Статистика"

mainapp/forms.py
from django import forms

from .models import EntryModel


class CreateEntryForm(forms.ModelForm):
    """Форма для создания и редактирования записи"""
    title = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Название записи",
        "style": "margin-top: 20px;"
    }))
    distance = forms.FloatField(widget=forms.NumberInput(attrs={
        "class": "form-control",
        "placeholder": "Расстояние (километры)",
        "style": "margin-top: 20px;"
    }))
    duration = forms.FloatField(widget=forms.NumberInput(attrs={
        "class": "form-control",
        "placeholder": "Продолжительность времени (часы)",
        "style": "margin-top: 20px;"
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].label = ""
        self.fields["distance"].label = ""
        self.fields["duration"].label = ""

    class Meta:
        model = EntryModel
        fields = [
            "title",
            "distance",
            "duration",
        ]

mainapp/views.py
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import View, ListView, UpdateView, DetailView, DeleteView
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect

from .models import EntryModel, StatisticModel
from .forms import CreateEntryForm
from .utils import add_to_statistic, filter_entries


User = get_user_model()


class ReadmeView(View):
    """представление страницы README"""
    def get(self, request, *args, **kwargs):
        return render(request, "mainapp/readme.html")


class EntryListView(LoginRequiredMixin, ListView):
    """вывод записей"""
    login_url = '/'
    redirect_field_name = None

    model = EntryModel
    template_name = "mainapp/entries.html"
    context_object_name = "entries"
    ordering = "-date"

    def get_queryset(self):
        return filter_entries(self)


class StatisticListView(LoginRequiredMixin, ListView):
    """вывод статистики"""
    login_url = '/'
    redirect_field_name = None

    model = StatisticModel
    template_name = "mainapp/statistic.html"
    context_object_name = "weeks"
    ordering = ("-year", "-week_number")


class CreateEntry(LoginRequiredMixin, View):
    """создание записи"""
    login_url = '/'
    redirect_field_name = None

    def get(self, request, *args, **kwargs):
        form = CreateEntryForm(request.POST or None)
        context = {
            "form": form,
        }
        return render(request, "mainapp/create_entry.html", context)

    def post(self, request, *args, **kwargs):
        form = CreateEntryForm(request.POST or None)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.user = User.objects.get(username=self.request.user.username)
            new_entry.average_speed = round(form.cleaned_data["distance"] / form.cleaned_data["duration"], 2)
            new_entry.save()
            add_to_statistic(new_entry)
            return HttpResponseRedirect("/entries/")
        context = {
            "form": form,
        }
        return render(request, "mainapp/create_entry.html", context)


class EntryUpdateView(LoginRequiredMixin, UpdateView):
    """редактирование записи"""
    login_url = '/'
    redirect_field_name = None

    model = EntryModel
    template_name = "mainapp/create_entry.html"
    form_class = CreateEntryForm

    def form_valid(self, form):
        new = form.save(commit=False)
        new.average_speed = round(form.cleaned_data["distance"] / form.cleaned_data["duration"], 2)
        new.save()
        return HttpResponseRedirect("/entries/")


class EntryDetailView(DetailView):
    """вывод одной записи"""
    login_url = '/'
    redirect_field_name = None

    model = EntryModel
    context_object_name = "entry"
    template_name = "mainapp/entry_detail.html"
    pk_url_kwarg = "pk"


class EntryDeleteView(DeleteView):
    """удаление записи из базы данных"""
    login_url = '/'
    redirect_field_name = None

    model = EntryModel
    template_name = "mainapp/entry_delete.html"
    success_url = "/entries/"

templates/mainapp/create_entry.html
{% extends "base/base.html" %}

{% block title %}Добавление / изменение запись{% endblock title %}

{% block main %}
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h3 class="h3">Добавление / изменение запись</h3>
                <br>
                <div class="features">
                    <form action="" method="post">
                        {% csrf_token %}
                        <p>{{ form.title }}</p>
                        <p>{{ form.distance }}</p>
                        <p>{{ form.duration }}</p>
                        <br>
                        <input type="submit" class="btn btn-success" value="Применить">
                    </form>
                </div>
            </div>
        </div>

{% endblock main %}

templates/mainapp/entries.html
{% extends "base/base.html" %}

{% block title %}Записи{% endblock title %}

{% block main %}

    <a class="btn btn-primary" href="{% url 'mainapp:create_entry_page' %}">Добавить запись</a>
    <h1 class="text-center" style="color: brown;">Записи</h1>
    {% include "include/filter_entries.html" %}
    {% for entry in entries %}
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <p><h3 class="h3">{{ entry.title }}</h3></p>
                <p><strong><i>Пользователь:</i></strong> {{ entry.user.username }}</p>
                <p><strong><i>Расстояние:</i></strong> {{ entry.distance }} км.</p>
                <p><strong><i>Продолжительность времени:</i></strong> {{ entry.duration }} ч.</p>
                <p><strong><i>Средняя скорость:</i></strong> {{ entry.average_speed }} км/ч</p>
                {% if request.user.username == entry.user.username %}
                <p>
                    <a class="btn btn-success" href="{% url 'mainapp:entry_detail_page' pk=entry.id %}">Подробнее</a>
                    <a class="btn btn-primary" href="{% url 'mainapp:update_entry_page' pk=entry.id %}">Редактировать</a>
                </p>
                {% endif %}
                <hr>
            </div>
        </div>
    {% endfor %}

{% endblock main %}

templates/mainapp/entry_delete.html
{% extends "base/base.html" }

{% extends "base/base.html" %}

{% block title %}{{entry.title}}{% endblock title %}

{% block main %}
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <div class="features">
                    <h3 class="h3">Вы хорошо подумали?</h3>
                    <br>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Удалить">
                    </form>
                </div>
            </div>
        </div>

{% endblock main %}

templates/mainapp/entry_detail.html
{% extends "base/base.html" %}

{% block title %}{{entry.title}}{% endblock title %}

{% block main %}
        {% if request.user.username == entry.user.username %}
            <div class="row text-center pt-3">
                <div class="col-lg-6 m-auto">
                    <p><h2 class="h2">{{ entry.title }}</h2></p>
                    <p><strong><i>Пользователь:</i></strong> {{ entry.user.username }}</p>
                    <p><strong><i>Расстояние:</i></strong> {{ entry.distance }} км.</p>
                    <p><strong><i>Продолжительность времени:</i></strong> {{ entry.duration }} ч.</p>
                    <p><strong><i>Средняя скорость:</i></strong> {{ entry.average_speed }} км/ч</p>
                    <p><strong><i>Дата добавления:</i></strong> {{ entry.date }}</p>
                    <p>
                        <a class="btn btn-primary" href="{% url 'mainapp:update_entry_page' pk=entry.id %}">Редактировать</a>
                        <a class="btn btn-danger" href="{% url 'mainapp:entry_delete_page' pk=entry.id %}">Удалить</a>
                    </p>
                </div>
            </div>
        {% else %}
            <h1>Error 403</h1>
        {% endif %}

{% endblock main %}

templates/mainapp/readme.html
{% extends "base/base.html" %}

{% block title %}README{% endblock title %}

{% block main %}

<div class="text-center">
    <h1>V2 - Report page</h1>
    <h5>ссылка на проект в GitHub - <a href="https://github.com/Rybak-a87/report_page-django">Rybak-a87/report_page-django</a></h5>
    <div class="col-lg-5 m-auto">
       <ul>
           <p><li>Анонимный пользователь может получить доступ только к странице README и формам входа или регистрации.</li></p>
           <p><li>Пользователь может создавать, удалять или просматривать список только своих записей</li></p>
           <p><li>Чтобы создать запись, пользователь предоставит следующие данные: дата, расстояние, продолжительность</li></p>
           <p><li>Когда пользователь видит список записей, приложение также показывает среднюю скорость</li></p>
           <p><li>Пользователь имеет возможность фильтровать список записей по диапазону дат.</li></p>
           <p><li>Есть страница с недельной статистикой за последний год - номер недели, общее количество записей,
            общее расстояние, общая продолжительность и средняя скорость за неделю.</li></p>
           <p><li>Минимальный внешний вид. Использовался bootstrap</li></p>
      </ul>
    </div>
</div>


{% endblock main %}

templates/mainapp/statistic.html
{% extends "base/base.html" %}
{% load calculate_total_sum %}


{% block title %}Статистика{% endblock title %}

{% block main %}

    <h1 class="text-center" style="color: brown;">Статистика</h1>
<div class="col-lg-7 m-auto text-center">
<table class="table table-success table-striped">
    <thead>
        <tr>
            <th scope="col">Год</th>
            <th scope="col">Номер недели</th>
            <th scope="col">Количество записей</th>
            <th scope="col">Общее расстояние</th>
            <th scope="col">Общая продолжительность времени</th>
            <th scope="col">Средняя скорость за неделю</th>
        </tr>
    </thead>
    <tbody>
        {% for week in weeks %}
            {% if week.entry.count > 0 %}
                {% sum_attrs week.entry.all as total %}
                <tr>
                    <td>{{ week.year }}</td>
                    <th scope="row">{{ week.week_number }}</th>
                    <td>{{ week.entry.count }}</td>
                    <td>{{ total.distance }} км.</td>
                    <td>{{ total.duration }} ч.</td>
                    <td>{{ total.average_speed }} км/ч</td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock main %}