account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views


app_name = "account"

urlpatterns = [
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("registration/", views.RegistrationView.as_view(), name="registration"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainapp.urls")),
    path("account/", include("account.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views


app_name = "mainapp"


urlpatterns = [
    path("", views.ReadmeView.as_view(), name="readme_page"),
    path("entries/", views.EntryListView.as_view(), name="entries_page"),
    path("statistic/", views.StatisticListView.as_view(), name="statistic_page"),
    path("create-entry/", views.CreateEntry.as_view(), name="create_entry_page"),
    path("update-entry/<int:pk>/", views.EntryUpdateView.as_view(), name="update_entry_page"),
    path("entry/<int:pk>/", views.EntryDetailView.as_view(), name="entry_detail_page"),
    path("delete-entry/<int:pk>/", views.EntryDeleteView.as_view(), name="entry_delete_page"),
]

templates/include/filter_entries.html
<form method="get">
    <p>Показать записи:</p>
    <p>
        С <input type="date" id="start" name="start_date" value="" min="2021-01-01">
        до <input type="date" id="end" name="end_date" value="" min="2021-01-01">
        <input type="submit" name="submit" value="Применить"/>
</form>

templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'mainapp:readme_page' %}">REPORT PAGE</a>
      <div class="navbar-collapse mx-5" id="navbarColor01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'mainapp:entries_page' %}">Записи</a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'mainapp:statistic_page' %}">Статистика</a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'mainapp:readme_page' %}">README</a>
          </li>
        </ul>

        <ul class="navbar-nav me-3 mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
            <li class="nav-item mx-3">
              <p class="btn btn-success">Здравствуй {{ request.user.username }}</p>
            </li>
            <li class="nav-item mx-3">
              <a class="btn btn-danger" href="{% url 'account:logout' %}">Выйти</a>
            </li>
          {% else %}
            <li class="nav-item mx-3">
              <a class="btn btn-primary" href="{% url 'account:login' %}">Авторизация</a>
            </li>
            <li class="nav-item mx-3">
              <a class="btn btn-primary" href="{% url 'account:registration' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>